/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTutorRouteImport } from './routes/api/tutor'
import { Route as AuthenticatedTutorRouteImport } from './routes/_authenticated/tutor'
import { Route as AuthenticatedSocialRouteImport } from './routes/_authenticated/social'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedFlashcardsRouteImport } from './routes/_authenticated/flashcards'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommandWordsRouteImport } from './routes/_authenticated/command-words'
import { Route as AuthenticatedSubjectsIndexRouteImport } from './routes/_authenticated/subjects/index'
import { Route as AuthenticatedMockIndexRouteImport } from './routes/_authenticated/mock/index'
import { Route as AuthenticatedSubjectsSlugRouteImport } from './routes/_authenticated/subjects/$slug'
import { Route as AuthenticatedProfileUsernameRouteImport } from './routes/_authenticated/profile/$username'
import { Route as AuthenticatedMockSubjectIdRouteImport } from './routes/_authenticated/mock/$subjectId'
import { Route as AuthenticatedTopicTopicIdIndexRouteImport } from './routes/_authenticated/topic/$topicId/index'
import { Route as AuthenticatedTopicTopicIdTutorRouteImport } from './routes/_authenticated/topic/$topicId/tutor'
import { Route as AuthenticatedTopicTopicIdQuizRouteImport } from './routes/_authenticated/topic/$topicId/quiz'
import { Route as AuthenticatedTopicTopicIdCardsRouteImport } from './routes/_authenticated/topic/$topicId/cards'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTutorRoute = ApiTutorRouteImport.update({
  id: '/api/tutor',
  path: '/api/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTutorRoute = AuthenticatedTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSocialRoute = AuthenticatedSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFlashcardsRoute = AuthenticatedFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommandWordsRoute =
  AuthenticatedCommandWordsRouteImport.update({
    id: '/command-words',
    path: '/command-words',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubjectsIndexRoute =
  AuthenticatedSubjectsIndexRouteImport.update({
    id: '/subjects/',
    path: '/subjects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMockIndexRoute = AuthenticatedMockIndexRouteImport.update({
  id: '/mock/',
  path: '/mock/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSubjectsSlugRoute =
  AuthenticatedSubjectsSlugRouteImport.update({
    id: '/subjects/$slug',
    path: '/subjects/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileUsernameRoute =
  AuthenticatedProfileUsernameRouteImport.update({
    id: '/profile/$username',
    path: '/profile/$username',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMockSubjectIdRoute =
  AuthenticatedMockSubjectIdRouteImport.update({
    id: '/mock/$subjectId',
    path: '/mock/$subjectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTopicTopicIdIndexRoute =
  AuthenticatedTopicTopicIdIndexRouteImport.update({
    id: '/topic/$topicId/',
    path: '/topic/$topicId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTopicTopicIdTutorRoute =
  AuthenticatedTopicTopicIdTutorRouteImport.update({
    id: '/topic/$topicId/tutor',
    path: '/topic/$topicId/tutor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTopicTopicIdQuizRoute =
  AuthenticatedTopicTopicIdQuizRouteImport.update({
    id: '/topic/$topicId/quiz',
    path: '/topic/$topicId/quiz',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTopicTopicIdCardsRoute =
  AuthenticatedTopicTopicIdCardsRouteImport.update({
    id: '/topic/$topicId/cards',
    path: '/topic/$topicId/cards',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/command-words': typeof AuthenticatedCommandWordsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/social': typeof AuthenticatedSocialRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/api/tutor': typeof ApiTutorRoute
  '/mock/$subjectId': typeof AuthenticatedMockSubjectIdRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/subjects/$slug': typeof AuthenticatedSubjectsSlugRoute
  '/mock/': typeof AuthenticatedMockIndexRoute
  '/subjects/': typeof AuthenticatedSubjectsIndexRoute
  '/topic/$topicId/cards': typeof AuthenticatedTopicTopicIdCardsRoute
  '/topic/$topicId/quiz': typeof AuthenticatedTopicTopicIdQuizRoute
  '/topic/$topicId/tutor': typeof AuthenticatedTopicTopicIdTutorRoute
  '/topic/$topicId/': typeof AuthenticatedTopicTopicIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/command-words': typeof AuthenticatedCommandWordsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/flashcards': typeof AuthenticatedFlashcardsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/social': typeof AuthenticatedSocialRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/api/tutor': typeof ApiTutorRoute
  '/mock/$subjectId': typeof AuthenticatedMockSubjectIdRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/subjects/$slug': typeof AuthenticatedSubjectsSlugRoute
  '/mock': typeof AuthenticatedMockIndexRoute
  '/subjects': typeof AuthenticatedSubjectsIndexRoute
  '/topic/$topicId/cards': typeof AuthenticatedTopicTopicIdCardsRoute
  '/topic/$topicId/quiz': typeof AuthenticatedTopicTopicIdQuizRoute
  '/topic/$topicId/tutor': typeof AuthenticatedTopicTopicIdTutorRoute
  '/topic/$topicId': typeof AuthenticatedTopicTopicIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/command-words': typeof AuthenticatedCommandWordsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/flashcards': typeof AuthenticatedFlashcardsRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/social': typeof AuthenticatedSocialRoute
  '/_authenticated/tutor': typeof AuthenticatedTutorRoute
  '/api/tutor': typeof ApiTutorRoute
  '/_authenticated/mock/$subjectId': typeof AuthenticatedMockSubjectIdRoute
  '/_authenticated/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/_authenticated/subjects/$slug': typeof AuthenticatedSubjectsSlugRoute
  '/_authenticated/mock/': typeof AuthenticatedMockIndexRoute
  '/_authenticated/subjects/': typeof AuthenticatedSubjectsIndexRoute
  '/_authenticated/topic/$topicId/cards': typeof AuthenticatedTopicTopicIdCardsRoute
  '/_authenticated/topic/$topicId/quiz': typeof AuthenticatedTopicTopicIdQuizRoute
  '/_authenticated/topic/$topicId/tutor': typeof AuthenticatedTopicTopicIdTutorRoute
  '/_authenticated/topic/$topicId/': typeof AuthenticatedTopicTopicIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/sitemap.xml'
    | '/command-words'
    | '/dashboard'
    | '/flashcards'
    | '/leaderboard'
    | '/notes'
    | '/settings'
    | '/social'
    | '/tutor'
    | '/api/tutor'
    | '/mock/$subjectId'
    | '/profile/$username'
    | '/subjects/$slug'
    | '/mock/'
    | '/subjects/'
    | '/topic/$topicId/cards'
    | '/topic/$topicId/quiz'
    | '/topic/$topicId/tutor'
    | '/topic/$topicId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/sitemap.xml'
    | '/command-words'
    | '/dashboard'
    | '/flashcards'
    | '/leaderboard'
    | '/notes'
    | '/settings'
    | '/social'
    | '/tutor'
    | '/api/tutor'
    | '/mock/$subjectId'
    | '/profile/$username'
    | '/subjects/$slug'
    | '/mock'
    | '/subjects'
    | '/topic/$topicId/cards'
    | '/topic/$topicId/quiz'
    | '/topic/$topicId/tutor'
    | '/topic/$topicId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/sitemap.xml'
    | '/_authenticated/command-words'
    | '/_authenticated/dashboard'
    | '/_authenticated/flashcards'
    | '/_authenticated/leaderboard'
    | '/_authenticated/notes'
    | '/_authenticated/settings'
    | '/_authenticated/social'
    | '/_authenticated/tutor'
    | '/api/tutor'
    | '/_authenticated/mock/$subjectId'
    | '/_authenticated/profile/$username'
    | '/_authenticated/subjects/$slug'
    | '/_authenticated/mock/'
    | '/_authenticated/subjects/'
    | '/_authenticated/topic/$topicId/cards'
    | '/_authenticated/topic/$topicId/quiz'
    | '/_authenticated/topic/$topicId/tutor'
    | '/_authenticated/topic/$topicId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiTutorRoute: typeof ApiTutorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tutor': {
      id: '/api/tutor'
      path: '/api/tutor'
      fullPath: '/api/tutor'
      preLoaderRoute: typeof ApiTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tutor': {
      id: '/_authenticated/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AuthenticatedTutorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/social': {
      id: '/_authenticated/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AuthenticatedSocialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flashcards': {
      id: '/_authenticated/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof AuthenticatedFlashcardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/command-words': {
      id: '/_authenticated/command-words'
      path: '/command-words'
      fullPath: '/command-words'
      preLoaderRoute: typeof AuthenticatedCommandWordsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subjects/': {
      id: '/_authenticated/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof AuthenticatedSubjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mock/': {
      id: '/_authenticated/mock/'
      path: '/mock'
      fullPath: '/mock/'
      preLoaderRoute: typeof AuthenticatedMockIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subjects/$slug': {
      id: '/_authenticated/subjects/$slug'
      path: '/subjects/$slug'
      fullPath: '/subjects/$slug'
      preLoaderRoute: typeof AuthenticatedSubjectsSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/$username': {
      id: '/_authenticated/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AuthenticatedProfileUsernameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mock/$subjectId': {
      id: '/_authenticated/mock/$subjectId'
      path: '/mock/$subjectId'
      fullPath: '/mock/$subjectId'
      preLoaderRoute: typeof AuthenticatedMockSubjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/topic/$topicId/': {
      id: '/_authenticated/topic/$topicId/'
      path: '/topic/$topicId'
      fullPath: '/topic/$topicId/'
      preLoaderRoute: typeof AuthenticatedTopicTopicIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/topic/$topicId/tutor': {
      id: '/_authenticated/topic/$topicId/tutor'
      path: '/topic/$topicId/tutor'
      fullPath: '/topic/$topicId/tutor'
      preLoaderRoute: typeof AuthenticatedTopicTopicIdTutorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/topic/$topicId/quiz': {
      id: '/_authenticated/topic/$topicId/quiz'
      path: '/topic/$topicId/quiz'
      fullPath: '/topic/$topicId/quiz'
      preLoaderRoute: typeof AuthenticatedTopicTopicIdQuizRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/topic/$topicId/cards': {
      id: '/_authenticated/topic/$topicId/cards'
      path: '/topic/$topicId/cards'
      fullPath: '/topic/$topicId/cards'
      preLoaderRoute: typeof AuthenticatedTopicTopicIdCardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCommandWordsRoute: typeof AuthenticatedCommandWordsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFlashcardsRoute: typeof AuthenticatedFlashcardsRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSocialRoute: typeof AuthenticatedSocialRoute
  AuthenticatedTutorRoute: typeof AuthenticatedTutorRoute
  AuthenticatedMockSubjectIdRoute: typeof AuthenticatedMockSubjectIdRoute
  AuthenticatedProfileUsernameRoute: typeof AuthenticatedProfileUsernameRoute
  AuthenticatedSubjectsSlugRoute: typeof AuthenticatedSubjectsSlugRoute
  AuthenticatedMockIndexRoute: typeof AuthenticatedMockIndexRoute
  AuthenticatedSubjectsIndexRoute: typeof AuthenticatedSubjectsIndexRoute
  AuthenticatedTopicTopicIdCardsRoute: typeof AuthenticatedTopicTopicIdCardsRoute
  AuthenticatedTopicTopicIdQuizRoute: typeof AuthenticatedTopicTopicIdQuizRoute
  AuthenticatedTopicTopicIdTutorRoute: typeof AuthenticatedTopicTopicIdTutorRoute
  AuthenticatedTopicTopicIdIndexRoute: typeof AuthenticatedTopicTopicIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCommandWordsRoute: AuthenticatedCommandWordsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFlashcardsRoute: AuthenticatedFlashcardsRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSocialRoute: AuthenticatedSocialRoute,
  AuthenticatedTutorRoute: AuthenticatedTutorRoute,
  AuthenticatedMockSubjectIdRoute: AuthenticatedMockSubjectIdRoute,
  AuthenticatedProfileUsernameRoute: AuthenticatedProfileUsernameRoute,
  AuthenticatedSubjectsSlugRoute: AuthenticatedSubjectsSlugRoute,
  AuthenticatedMockIndexRoute: AuthenticatedMockIndexRoute,
  AuthenticatedSubjectsIndexRoute: AuthenticatedSubjectsIndexRoute,
  AuthenticatedTopicTopicIdCardsRoute: AuthenticatedTopicTopicIdCardsRoute,
  AuthenticatedTopicTopicIdQuizRoute: AuthenticatedTopicTopicIdQuizRoute,
  AuthenticatedTopicTopicIdTutorRoute: AuthenticatedTopicTopicIdTutorRoute,
  AuthenticatedTopicTopicIdIndexRoute: AuthenticatedTopicTopicIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiTutorRoute: ApiTutorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
