ALTER TABLE public.blog_posts ADD COLUMN IF NOT EXISTS og_image text;

UPDATE public.blog_posts SET og_image = 'https://alevelace.lovable.app/og/blog-study-tips.jpg'
WHERE slug IN ('a-level-study-tips-that-actually-work', 'flashcards-spaced-repetition-guide', 'a-star-study-plan-template');
UPDATE public.blog_posts SET og_image = 'https://alevelace.lovable.app/og/blog-exam-day.jpg'
WHERE slug IN ('how-to-use-past-papers-properly', 'mock-exam-strategy');

INSERT INTO public.blog_posts (slug, title, excerpt, content, tags, read_minutes, published, published_at, og_image) VALUES
('exam-day-strategies-that-win-marks',
 'Exam-day strategies that actually win marks',
 'Timing plans, question triage, checking routines and the calm habits that stop you throwing away marks you already earned.',
 '## Before the paper\n\nPack the night before: pens (two black), pencil, ruler, calculator with fresh batteries, and your statement of entry. Set two alarms. Cramming at 2am costs more marks than it gains — sleep consolidates memory.\n\n## The first five minutes\n\n1. Read the whole paper before writing anything.\n2. Mark the questions you can do cold with a tick.\n3. Note the mark tariff of each section — this sets your pace.\n\n## Timing: the marks-per-minute rule\n\nDivide the time by the total marks. A 75-mark, 90-minute paper gives you roughly 1.2 minutes per mark. A 10-marker gets 12 minutes, then you move on. Leaving a hard question to finish easier ones is not giving up — it is mark-maximising.\n\n## Question triage\n\nDo questions in this order:\n\n- **Green:** you know the method immediately — do these first and bank the marks.\n- **Amber:** you know the topic but need thinking time — second pass.\n- **Red:** no idea — last. Even then, write the formula, a labelled diagram, or the first line of the method. M1 marks are often given for a correct start.\n\n## The checking routine\n\nWith 10 minutes left:\n\n- Check every numerical answer has the right units and sensible magnitude.\n- In maths, substitute your answer back into the equation.\n- In essays, check you actually answered the command word — "evaluate" needs a judgement, not a description.\n\n## If you panic\n\nStop writing. Both feet on the floor, slow breath in for four counts, out for six. Thirty seconds of calm recovers more than thirty seconds of frozen staring. Then write down anything you know about the topic — momentum returns quickly.\n\nPractise these habits under real timing with a timed mock on A-Level Ace before the real day.',
 '{"exam technique","revision","exam day"}', 6, true, now(), 'https://alevelace.lovable.app/og/blog-exam-day.jpg'),

('a-level-maths-subject-guide',
 'A-Level Maths subject guide: what the examiners really want',
 'Pure, mechanics and statistics for CIE 9709 and Edexcel 9MA0 — the topics that carry the most marks and how to revise each one.',
 '## How the qualification is structured\n\n**CIE 9709:** Paper 1 (Pure 1, AS), Paper 3 (Pure 3, A2), plus two applied papers chosen from Mechanics (Paper 4), Probability & Statistics 1 (Paper 5) and Statistics 2 (Paper 6).\n\n**Edexcel 9MA0:** Paper 1 and Paper 2 (Pure), Paper 3 (Statistics & Mechanics).\n\n## The high-yield pure topics\n\n- **Differentiation and integration** — appear in nearly every question, directly or inside another topic. Master the chain, product and quotient rules, integration by substitution and by parts (A2), and kinematics applications.\n- **Trigonometry** — identities, the R cos(θ − α) form, and equations with multiple solutions in a range. Losing a solution here is the single most common A* slip.\n- **Sequences and series** — geometric series with |r| < 1, binomial expansion for rational n (A2).\n- **Vectors** — scalar product, angles between lines, and shortest-distance problems.\n\n## How to revise maths (not just read it)\n\n1. Work every problem on paper, timed. Watching solutions is not revision.\n2. After each past paper, log every lost mark as knowledge, method (M1) or accuracy (A1). Most students discover 60% of losses are accuracy — fixable with checking routines.\n3. Redo every question you got wrong, three days later, from a blank page.\n\n## Mark scheme literacy\n\n- **M marks** are for method — write the method even if the arithmetic fails.\n- **A marks** depend on the preceding M. No method, no accuracy mark.\n- **B marks** are independent — correct results like exact values, stated without working, still score.\n\nOn A-Level Ace, generate a Pure 1 or Pure 3 mock and let the AI marker annotate your script with M1/A1/B1 reasoning.',
 '{"maths","subject guide","CIE","Edexcel"}', 7, true, now(), 'https://alevelace.lovable.app/og/blog-subject-guides.jpg'),

('a-level-physics-subject-guide',
 'A-Level Physics subject guide: from formulas to full marks',
 'Mechanics, fields, quantum and the required practicals for CIE 9702 and Edexcel 9PH0 — plus how to write explanations examiners accept.',
 '## The structure\n\n**CIE 9702:** Papers 1–3 at AS (MCQ, structured questions, practical), Papers 4–5 at A2 (structured, planning/analysis).\n\n**Edexcel 9PH0:** Paper 1 (advanced physics I), Paper 2 (advanced physics II), Paper 3 (synoptic, including practical skills).\n\n## Where the marks concentrate\n\n- **Mechanics:** suvat, Newton''s laws, moments, energy and momentum. Free-body diagrams earn marks on their own — always draw one.\n- **Electricity and fields:** circuits with internal resistance, Coulomb''s law, electric and gravitational field analogies, capacitors (A2).\n- **Waves and quantum:** superposition, stationary waves, the photoelectric effect — quote \[ E = hf = \phi + \tfrac{1}{2}mv_{max}^2 \] and define every term.\n- **Thermal and nuclear (A2):** ideal gases, radioactive decay with \[ N = N_0 e^{-\lambda t} \], binding energy.\n\n## Writing explanations that score\n\nPhysics explanations are marked in a strict logical chain. Each sentence must cause the next:\n\n> "As temperature rises, the atoms vibrate with greater amplitude, so electrons collide with the lattice more frequently, so resistance increases."\n\nOne causal step per sentence, linked with "so" or "therefore". Vague words like "it affects" score nothing.\n\n## Practicals are examined\n\nBoth boards test practical technique in written papers: plotting graphs (points cover less than half the grid is a classic lost mark), gradients with large triangles, uncertainty calculations and percentage uncertainty propagation. Revise the required practicals by name.\n\n## Units and sig figs\n\nFinal answers: correct unit, 2–3 significant figures, and sensible magnitude checks. These are free marks students donate every session.',
 '{"physics","subject guide","practicals"}', 7, true, now(), 'https://alevelace.lovable.app/og/blog-subject-guides.jpg'),

('a-level-economics-subject-guide',
 'A-Level Economics subject guide: diagrams, chains and AJIM evaluation',
 'Micro and macro for CIE 9708 and Edexcel 9EC0 — how to draw the diagrams, build analysis chains and evaluate like an A* candidate.',
 '## The structure\n\n**CIE 9708:** Papers 1–2 at AS (MCQ, data response & essay), Papers 3–4 at A2 (MCQ, data response & essays).\n\n**Edexcel 9EC0:** Paper 1 (markets & business behaviour), Paper 2 (national & global economy), Paper 3 (micro & macro synoptic).\n\n## Diagrams: the non-negotiables\n\nEvery diagram mark requires:\n\n- **Axes labelled** with the variable, not just "P" and "Q" — "Price (£)" and "Quantity (units)".\n- **Correct shift direction** — state what shifts and why before you draw it.\n- **New equilibrium marked** — new price and quantity labelled on the axes, with dashed lines.\n- **Referenced in your writing** — "as shown in Figure 1, the supply curve shifts left from S1 to S2".\n\nAn unlabelled or unreferenced diagram scores zero, however beautiful.\n\n## Analysis chains\n\nTop-band answers argue in connected steps: policy or event → mechanism → effect on agents → effect on the macro objective. Four to six links, each with "this means", "leading to", "consequently". Practise extending a chain one link further than feels necessary.\n\n## AJIM evaluation\n\nEvaluation separates A from A*. For every argument, run **AJIM**:\n\n- **A — Answer** the question directly with a judgement.\n- **J — Justify** it with the strongest argument.\n- **I — It depends on:** elasticity, time lag, magnitude, the state of the economy. Name the specific dependency.\n- **M — Most important factor:** state which consideration dominates and why, in this context.\n\n"It depends on the price elasticity of demand — if demand is inelastic, the tax mainly raises revenue rather than cutting consumption" is a grade-A* sentence. "However, some disagree" is not evaluation.\n\n## Policy trade-offs to have ready\n\n- Inflation vs unemployment (Phillips curve)\n- Growth vs environmental sustainability\n- Free trade vs protectionism\n- Fiscal stimulus vs national debt\n\nBuild these once, then reuse them across every macro essay.',
 '{"economics","subject guide","essay technique"}', 8, true, now(), 'https://alevelace.lovable.app/og/blog-subject-guides.jpg')
ON CONFLICT (slug) DO NOTHING;